version: '3'

services:
  mongodb:
    image: mongo:latest
    ports:
      - '27018:27017'
    volumes:
      - mongo_data:/data/db

  flashcardsapi:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - mongodb
    environment:
      MONGODB_URI: mongodb://mongodb:27017/flashcardsDB

volumes:
  mongo_data:
