version: '3.8'

services:
  api:
    image: ${API_CONTAINER_NAME}
    container_name: ${API_CONTAINER_NAME}
    restart: always
    build: .
    ports:
      - '${API_PORT}:${API_INTERNAL_PORT}'
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - network

  mongo_db:
    container_name: ${MONGO_DB_CONTAINER_NAME}
    image: mongo:latest
    logging:
      driver: none
    command: mongod --quiet --logpath /dev/null
    ports:
      - '${MONGO_LOCAL_PORT}:${MONGO_INTERNAL_PORT}'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
    env_file:
      - .env
    volumes:
      - mongo_data:/data/db
    networks:
      - network

  mongo_backup:
    profiles: ["backup"]
    container_name: ${MONGO_BACKUP_CONTAINER_NAME}
    image: mongo:latest
    logging:
      driver: none
    depends_on:
      - mongo_db
    volumes:
      - ./mongo_backups:/backup
    entrypoint: >
      /bin/sh -c "while true; do
        mongodump --quiet --host mongo_db --username ${MONGO_INITDB_ROOT_USERNAME} --password ${MONGO_INITDB_ROOT_PASSWORD} --authenticationDatabase admin --out /backup/latest;
        sleep 86400;
      done"
    networks:
      - network

networks:
  network:
    name: flashcards_network
    driver: bridge

volumes:
  mongo_data:
